name: Test

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Add value to .env file
        id: time
        run: |
          touch .env
          echo "YOUR_KEY=${{ secrets.SECRET }}" >> .env
        
    
      - name: Log content of file
        run: .env
