name: Test

on:
  workflow_dispatch:

jobs:
  build::
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v3
      - name: Add value to .env file
          run: echo "YOUR_KEY=YOUR_VALUE" >> .env 
        
    
